### ISSUE TITLE
Which has no -s option

### ISSUE THREAD

**Issue by sweepyoface** [jaygooby/ttfb.sh#2]
At
https://github.com/jaygooby/ttfb.sh/blob/c8088c7f630c053a2d8c2af101e8aaff9c56c72d/ttfb#L65
an invalid `-s` option for `which` is specified, and it expectedly complains:
```
Illegal option -s
Usage: /usr/bin/which [-a] args
You need to have 'curl' installed and in your $PATH
```

You can see that it doesn't exist on the gnu which [man page](https://linux.die.net/man/1/which).

Looks like the intention is for it to be silent, so it can simply be replaced with
```sh
which $dependency > /dev/null
```
which is tested and working.

**Comment by jaygooby** [comment]
Thanks, yeah. Looks like `-s`  is BSD `which` specific. Thanks 🎉
