### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by jaygooby** [jaygooby/ttfb.sh#7]
See e.g. #6

**Comment by thanghl** [comment]
i tessting another site have problem 
./ttfb https://www.radiantmediaplayer.com/media/bbb-360p.mp4
curl: option --http2: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
curl: option --http1.1: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

thanks for help

**Comment by jaygooby** [comment]
Can you run `curl --version` and tell me what version you have?

**Comment by jaygooby** [comment]
Fixed in 91886e3d272dcbf50fa6a9e138a44af01e9bf9ac and a test suite added in https://github.com/jaygooby/ttfb.sh/commit/5ea1b838a7c211a34aeb66c88585fcd473485c53
